### ISSUE TITLE
Wallet breaks if token.USD === null when accessing Tx Form for that token

### ISSUE THREAD

**Issue by AlbertoElias** [hermeznetwork/wallet-ui#685] opened 2021-09-29 15:41 UTC
If in the API request to /tokens, one of the tokens has a USD value of null (or undefined), the wallet has an uncaught error in Tx Form. We should just show -- in the fiat values instead of breaking completely.

**Comment by amonsosanz** [comment] 2021-11-23 10:44
According to our domain definition, `token.USD === null` is not a supported case. If it's legit for a `Token` to have `null` in its `USD` prop, the domain must reflect it and persistence must also take it into account.

**Comment by amonsosanz** [comment] 2022-01-03 14:53
This should have been fixed in [this PR](https://github.com/hermeznetwork/wallet-ui/pull/795/files#diff-119553cba46b6e3b670cbbdc90775303e05395a624ded0cbbe1800862be26d18R30).  Please try to reproduce the error before fixing it, since now the property `Token.USD` is already nullable at domain level.

**Closed** 2022-01-12 12:07 UTC
Labels: type: bug, priority: low
