### ISSUE TITLE
Approve popup is always displayed before the deposit signing popup

### ISSUE THREAD

**Issue by elias-garcia** [hermeznetwork/wallet-ui#453] opened 2021-04-27 14:55 UTC
When you are going to deposit some ERC-20 tokens and you have already done an approval and you reject to sign a transaction, if you start again this process it will require you to approve the tokens again. The wallet should me smart enough to know that the tokens had being already approved and display the popup just for signing the transaction.

**Comment by AlbertoElias** [comment] 2021-05-14 07:54
This only happens if the approve tx has been confirmed. We need to rethink the whole approval process, there's a meeting next week for this

**Comment by AlbertoElias** [comment] 2021-05-19 10:15
Closing this as it's a duplicate of #461

**Closed by AlbertoElias** 2021-05-19 10:15 UTC
Labels: type: enhancement
